sampleParams:
  Reads: "*R1*fastq*"
  sampleid: ""
  library: ""

refs:
  Reference: "/home/GRCh38_full_analysis_set_plus_decoy_hla.fa"

bwamemParams:
  bwaThreads: 10

bcftoolsParams:
  bcfThreads: 4

bqsrParam:
  dbSNP: "/mnt/data0/GenomeResources/Snps/dbsnp_138.hg38.vcf.gz"
  indelFile: "/mnt/data0/GenomeResources/Snps/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  thousandGenomesSite: "/mnt/data0/GenomeResources/Snps/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  javaoptions: "-Djava.io.tmpdir=/mnt/scratch0/samtmp"